# 1. Базовый образ с Python
FROM python:3.13-slim

# 2. Рабочая директория
WORKDIR /app

# 3. Копируем requirements.txt и устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Копируем весь код
COPY . .

# 5. Задаём команду запуска FastAPI (uvicorn)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
